AI Job-Match Analyzer

In [11]:
import numpy as np 
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [12]:
df = pd.read_csv('resume_dataset.csv')
df.head()

,id,category,skills,education,experience,text,html
0,21614256,ADVOCATE,"Word programs (including Excel and Access), EP...","Boston University, Master of Public Health, Ep...","Bilingual Domestic Violence Advocate, Intern, ...",BILINGUAL DOMESTIC VIOLENCE ADVOCATE ...,"<div class=""fontsize fontface vmargins hmargin..."
1,97405769,ADVOCATE,"Superb sales professional, Store planning and ...","William Penn Vo-tech, General-Business, High S...","Customer Service Advocate, Sales Manager, Sale...",CUSTOMER SERVICE ADVOCATE Summa...,"<div class=""fontsize fontface vmargins hmargin..."
2,95970987,ADVOCATE,"Domestic Violence, Sexual Abuse, Rape, Prostit...","Boricua College, Human Services Psychology and...","Clinical Service Advocate, Women's Empowerment...",CLINICAL SERVICE ADVOCATE Profe...,"<div class=""fontsize fontface vmargins hmargin..."
3,17021141,ADVOCATE,"Accounting, Cashiering, Coaching, Computer tra...",University of Phoenix - Master of Business Adm...,"PH Inpatient/Financial Advocate Supervisor, PH...",PH INPATIENT/FINANCIAL ADVOCATE SUPER...,"<div class=""fontsize fontface vmargins hmargin..."
4,15337481,ADVOCATE,"Microsoft Suite Proficiency, RightFax Ventura,...","El Centro Community College, Health Administra...","Customer Service Advocate, Collection Speciali...",CUSTOMER SERVICE ADVOCATE Summa...,"<div class=""fontsize fontface vmargins hmargin..."

In [13]:
df.shape

(2257, 7)

In [14]:
df.columns

Index(['id', 'category', 'skills', 'education', 'experience', 'text', 'html'], dtype='str')

In [15]:
df.isnull().sum()

id            0
category      0
skills        0
education     0
experience    0
text          0
html          0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.drop(columns=['html'], inplace= True)

In [19]:
df.head(3)

,id,category,skills,education,experience,text
0,21614256,ADVOCATE,"Word programs (including Excel and Access), EP...","Boston University, Master of Public Health, Ep...","Bilingual Domestic Violence Advocate, Intern, ...",BILINGUAL DOMESTIC VIOLENCE ADVOCATE ...
1,97405769,ADVOCATE,"Superb sales professional, Store planning and ...","William Penn Vo-tech, General-Business, High S...","Customer Service Advocate, Sales Manager, Sale...",CUSTOMER SERVICE ADVOCATE Summa...
2,95970987,ADVOCATE,"Domestic Violence, Sexual Abuse, Rape, Prostit...","Boricua College, Human Services Psychology and...","Clinical Service Advocate, Women's Empowerment...",CLINICAL SERVICE ADVOCATE Profe...